global:
  registry: 033691785857.dkr.ecr.us-east-1.amazonaws.com
  domain: mosaiclife.me
web:
  enabled: true
coreApi:
  enabled: true
externalSecrets:
  session:
    secretKey: ""  # Required override per environment
